language: ruby

rvm:
  - 1.9.3

install:
  - bundle install

script:
  - bundle exec jekyll build

after_success:
  - bundle exec s3_website push --headless

env:
  global:
    - secure: HmwUnlM6UqLO4yfugVqy5aF/Lg3rQAQlUWIDr4P4k3oUp2U7HiXelBPwjRFc5vs2woSjJ4rrGqnd9HYGkmXuQlksFHEcbh/aBYR0hg265I2HU4TXECjQaChkwXjPFEyUkFbJrcPY3N6zV4Ef8SkJWJCRnwA6LHaV0ESymIAiRXk=
    - secure: UgsXfTdVZ3re4mAWZ9cucl2l5tcSKtNLDTxHI2pW50y1LzIbbLeoV8U+KZLxZS07iaGlg0vT2PkBrUuurlHGmCQKJ8+gY/EEmOhiHE4BJC9+9MHbLt2I4NWRX52mEFdE0dzeovQZ4dzpEdTHEPv6b7zJUkLpCcG77/qFnOOQkPY=
